"""Deterministic Niwes scan report generator (no LLM).

Produces markdown report with 6 sections from screener output:
  1. YAML frontmatter (agent, date, type, scan_num, scoring_version)
  2. Header + summary line
  3. Top Picks (top 10 candidates by score, with tag narratives)
  4. Review Candidates (REVIEW bucket from 3-tier hard filter)
  5. New In Batch (diff vs prev_scan)
  6. Watchlist Exit Alerts (grouped by severity)
  7. Watch Out (DIVIDEND_TRAP + DATA_WARNING)

Pattern narratives loaded from case_study_patterns.json. Same input = same output (deterministic).
"""
from datetime import datetime
from pathlib import Path
import json

_PATTERNS_PATH = Path(__file__).resolve().parent.parent / "data" / "case_study_patterns.json"
_PATTERNS = json.loads(_PATTERNS_PATH.read_text(encoding="utf-8")) if _PATTERNS_PATH.exists() else {}
_TAG_NARRATIVES = {k: v.get("narrative", "") for k, v in _PATTERNS.items()}
_TAG_NARRATIVES.update({
    "NIWES_5555": "ผ่านเกณฑ์ 5-5-5-5 ครบ (yield≥5 / streak≥5 / EPS 5yr+ / PE≤15 / PBV≤1.5)",
    "BRAND_MOAT": "Brand moat — margin สูง + dividend streak ยาว",
    "STRUCTURAL_MOAT": "Structural moat — utility/transport/telecom scale ใหญ่",
    "GOVT_LOCKIN": "Government lock-in — recurring revenue จากภาครัฐ",
    "HIDDEN_VALUE": "มี holding ที่ตลาดไม่ได้ pricing in",
    "DEEP_VALUE": "PE ≤8 + PBV ≤1.0 — ถูกกว่าค่าเฉลี่ย",
    "QUALITY_DIVIDEND": "yield ≥5% + payout <70% + streak ≥10 ปี",
    "DIVIDEND_TRAP": "ระวัง — yield >8% + ROE declining + payout >100%",
    "DATA_WARNING": "ข้อมูลผิดปกติ — ตรวจสอบก่อนใช้",
    "OVERPRICED": "valuation grade F — แพงกว่าคุณภาพ",
})


def _fm(date: str, scan_num: int, version: str) -> str:
    return f"---\nagent: Max Mahon v5\ndate: {date}\ntype: scan\nscan_num: {scan_num}\nscoring_version: {version}\n---\n"


def _top_pick_md(c: dict) -> str:
    sig_lines = "\n".join(f"- `{s}` — {_TAG_NARRATIVES.get(s, '')}" for s in c.get("signals", []))
    m = c.get("metrics", {}) or {}
    a = c.get("aggregates", {}) or {}
    yield_v = m.get("dy", 0) or 0
    pe_v = m.get("pe", "-") if m.get("pe") is not None else "-"
    pbv_v = c.get("pb_ratio") or m.get("pb_ratio", "-")
    if pbv_v is None:
        pbv_v = "-"
    streak = a.get("dividend_streak", 0)
    return (
        f"### {c['symbol']} — {c.get('name','')}\n"
        f"Sector: {c.get('sector','N/A')} · Score {c.get('score',0)}/100\n\n"
        f"- Yield {yield_v:.2f}% · PE {pe_v} · PBV {pbv_v} · Streak {streak}y\n"
        + sig_lines
        + "\n\n**Reasons:** " + "; ".join(c.get("reasons", [])[:5]) + "\n"
    )


def _diff_new(current: list, prev: list) -> list:
    prev_syms = {c.get("symbol") for c in (prev or [])}
    return [c for c in current if c.get("symbol") not in prev_syms]


def generate_report_md(screener_data: dict, scan_num: int, prev_scan: dict | None = None) -> str:
    date = screener_data.get("date", datetime.now().strftime("%Y-%m-%d"))
    version = screener_data.get("scoring_version", "niwes-dividend-first-v2")
    cands = screener_data.get("candidates", [])
    review = screener_data.get("review_candidates", [])
    top = sorted(cands, key=lambda x: x.get("score", 0), reverse=True)[:10]
    new_in = _diff_new(top, (prev_scan or {}).get("top_candidates", []))

    alerts_high: list[str] = []
    alerts_med: list[str] = []
    for c in cands:
        for t in c.get("exit_triggers", []):
            entry = f"- **{c['symbol']}** `{t.get('type','')}` — {t.get('reason','')}"
            if t.get("severity") == "high":
                alerts_high.append(entry)
            else:
                alerts_med.append(entry)

    warn = [c for c in cands if any(s in c.get("signals", []) for s in ["DIVIDEND_TRAP", "DATA_WARNING"])]

    parts = [
        _fm(date, scan_num, version),
        f"# รายงานตรวจหุ้น Niwes 5-5-5-5 (รอบที่ {scan_num})\n",
        f"_วันที่ {date} · ผ่าน {len(cands)} · review {len(review)} · new {len(new_in)}_\n",
        "## Top Picks\n\n" + ("\n".join(_top_pick_md(c) for c in top) or "_ไม่มีหุ้นผ่านรอบนี้_"),
        "\n## Review Candidates\n\n" + (
            "\n".join(
                f"- **{r['symbol']}** ({r.get('sector','')}) — {'; '.join(r.get('review_reasons', []))}"
                for r in review
            ) or "_ไม่มี_"
        ),
        "\n## New In Batch\n\n" + ("\n".join(f"- {c['symbol']}" for c in new_in) or "_ไม่มี_"),
        "\n## Watchlist Exit Alerts\n\n**High:**\n" + ("\n".join(alerts_high) or "_ไม่มี_")
            + "\n\n**Medium:**\n" + ("\n".join(alerts_med) or "_ไม่มี_"),
        "\n## Watch Out\n\n" + ("\n".join(f"- **{c['symbol']}** — {', '.join(c.get('signals', []))}" for c in warn) or "_ไม่มี_"),
        f"\n---\n_Generated by Max Mahon algo · scoring_version={version} · {datetime.now().isoformat(timespec='seconds')}_\n",
    ]
    return "\n".join(parts)


if __name__ == "__main__":
    import sys
    if len(sys.argv) >= 3 and sys.argv[1] == "--test":
        data = json.loads(Path(sys.argv[2]).read_text(encoding="utf-8"))
        print(generate_report_md(data, 0))
